package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AsuntoRelevante generated by hbm2java
 */
public class AsuntoRelevante  implements java.io.Serializable {


     private long asuntoId;
     private String asuntoNombre;
     private Set<SubsectorAsunto> subsectorAsuntos = new HashSet<SubsectorAsunto>(0);

    public AsuntoRelevante() {
    }

	
    public AsuntoRelevante(long asuntoId) {
        this.asuntoId = asuntoId;
    }
    public AsuntoRelevante(long asuntoId, String asuntoNombre, Set<SubsectorAsunto> subsectorAsuntos) {
       this.asuntoId = asuntoId;
       this.asuntoNombre = asuntoNombre;
       this.subsectorAsuntos = subsectorAsuntos;
    }
   
    public long getAsuntoId() {
        return this.asuntoId;
    }
    
    public void setAsuntoId(long asuntoId) {
        this.asuntoId = asuntoId;
    }
    public String getAsuntoNombre() {
        return this.asuntoNombre;
    }
    
    public void setAsuntoNombre(String asuntoNombre) {
        this.asuntoNombre = asuntoNombre;
    }
    public Set<SubsectorAsunto> getSubsectorAsuntos() {
        return this.subsectorAsuntos;
    }
    
    public void setSubsectorAsuntos(Set<SubsectorAsunto> subsectorAsuntos) {
        this.subsectorAsuntos = subsectorAsuntos;
    }




}


