package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FocoInversionSocial generated by hbm2java
 */
public class FocoInversionSocial  implements java.io.Serializable {


     private long foinsoId;
     private String foinsoNombre;
     private Set<SubsectorFoco> subsectorFocos = new HashSet<SubsectorFoco>(0);

    public FocoInversionSocial() {
    }

	
    public FocoInversionSocial(long foinsoId) {
        this.foinsoId = foinsoId;
    }
    public FocoInversionSocial(long foinsoId, String foinsoNombre, Set<SubsectorFoco> subsectorFocos) {
       this.foinsoId = foinsoId;
       this.foinsoNombre = foinsoNombre;
       this.subsectorFocos = subsectorFocos;
    }
   
    public long getFoinsoId() {
        return this.foinsoId;
    }
    
    public void setFoinsoId(long foinsoId) {
        this.foinsoId = foinsoId;
    }
    public String getFoinsoNombre() {
        return this.foinsoNombre;
    }
    
    public void setFoinsoNombre(String foinsoNombre) {
        this.foinsoNombre = foinsoNombre;
    }
    public Set<SubsectorFoco> getSubsectorFocos() {
        return this.subsectorFocos;
    }
    
    public void setSubsectorFocos(Set<SubsectorFoco> subsectorFocos) {
        this.subsectorFocos = subsectorFocos;
    }
    




}


