package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oportunidad generated by hbm2java
 */
public class Oportunidad  implements java.io.Serializable {


     private long oportunidadId;
     private String oportunidadDescripcion;
     private Set<SubsectorOportunidad> subsectorOportunidads = new HashSet<SubsectorOportunidad>(0);

    public Oportunidad() {
    }

	
    public Oportunidad(long oportunidadId) {
        this.oportunidadId = oportunidadId;
    }
    public Oportunidad(long oportunidadId, String oportunidadDescripcion, Set<SubsectorOportunidad> subsectorOportunidads) {
       this.oportunidadId = oportunidadId;
       this.oportunidadDescripcion = oportunidadDescripcion;
       this.subsectorOportunidads = subsectorOportunidads;
    }
   
    public long getOportunidadId() {
        return this.oportunidadId;
    }
    
    public void setOportunidadId(long oportunidadId) {
        this.oportunidadId = oportunidadId;
    }
    public String getOportunidadDescripcion() {
        return this.oportunidadDescripcion;
    }
    
    public void setOportunidadDescripcion(String oportunidadDescripcion) {
        this.oportunidadDescripcion = oportunidadDescripcion;
    }
    public Set<SubsectorOportunidad> getSubsectorOportunidads() {
        return this.subsectorOportunidads;
    }
    
    public void setSubsectorOportunidads(Set<SubsectorOportunidad> subsectorOportunidads) {
        this.subsectorOportunidads = subsectorOportunidads;
    }




}


