package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1



/**
 * Recomendacion generated by hbm2java
 */
public class Recomendacion  implements java.io.Serializable {


     private long recomendacionId;
     private Dimension dimension;
     private String recomendacionDescripcion;

    public Recomendacion() {
    }

	
    public Recomendacion(long recomendacionId) {
        this.recomendacionId = recomendacionId;
    }
    public Recomendacion(long recomendacionId, Dimension dimension, String recomendacionDescripcion) {
       this.recomendacionId = recomendacionId;
       this.dimension = dimension;
       this.recomendacionDescripcion = recomendacionDescripcion;
    }
   
    public long getRecomendacionId() {
        return this.recomendacionId;
    }
    
    public void setRecomendacionId(long recomendacionId) {
        this.recomendacionId = recomendacionId;
    }
    public Dimension getDimension() {
        return this.dimension;
    }
    
    public void setDimension(Dimension dimension) {
        this.dimension = dimension;
    }
    public String getRecomendacionDescripcion() {
        return this.recomendacionDescripcion;
    }
    
    public void setRecomendacionDescripcion(String recomendacionDescripcion) {
        this.recomendacionDescripcion = recomendacionDescripcion;
    }




}


