package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Proxy;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private String sectorNombre;
     private Set<Subsector> subsectors = new HashSet<Subsector>(0);

    public Sector() {
    }

	
    public Sector(String sectorNombre) {
        this.sectorNombre = sectorNombre;
    }
    public Sector(String sectorNombre, Set<Subsector> subsectors) {
       this.sectorNombre = sectorNombre;
       this.subsectors = subsectors;
    }
   
    public String getSectorNombre() {
        return this.sectorNombre;
    }
    
    public void setSectorNombre(String sectorNombre) {
        this.sectorNombre = sectorNombre;
    }
    public Set<Subsector> getSubsectors() {
        return this.subsectors;
    }
    
    public void setSubsectors(Set<Subsector> subsectors) {
        this.subsectors = subsectors;
    }




}


