package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Proxy;

/**
 * Subsector generated by hbm2java
 */
public class Subsector  implements java.io.Serializable {


     private String subsectorNombre;
     private Sector sector;
     private Set<SubsectorAsunto> subsectorAsuntos = new HashSet<SubsectorAsunto>(0);
     private Set<SubsectorOportunidad> subsectorOportunidads = new HashSet<SubsectorOportunidad>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<SubsectorFoco> subsectorFocos = new HashSet<SubsectorFoco>(0);

    public Subsector() {
    }

	
    public Subsector(String subsectorNombre) {
        this.subsectorNombre = subsectorNombre;
    }
    public Subsector(String subsectorNombre, Sector sector, Set<SubsectorAsunto> subsectorAsuntos, Set<SubsectorOportunidad> subsectorOportunidads, Set<Usuario> usuarios, Set<SubsectorFoco> subsectorFocos) {
       this.subsectorNombre = subsectorNombre;
       this.sector = sector;
       this.subsectorAsuntos = subsectorAsuntos;
       this.subsectorOportunidads = subsectorOportunidads;
       this.usuarios = usuarios;
       this.subsectorFocos = subsectorFocos;
    }
   
    public String getSubsectorNombre() {
        return this.subsectorNombre;
    }
    
    public void setSubsectorNombre(String subsectorNombre) {
        this.subsectorNombre = subsectorNombre;
    }
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }
    public Set<SubsectorAsunto> getSubsectorAsuntos() {
        return this.subsectorAsuntos;
    }
    
    public void setSubsectorAsuntos(Set<SubsectorAsunto> subsectorAsuntos) {
        this.subsectorAsuntos = subsectorAsuntos;
    }
    public Set<SubsectorOportunidad> getSubsectorOportunidads() {
        return this.subsectorOportunidads;
    }
    
    public void setSubsectorOportunidads(Set<SubsectorOportunidad> subsectorOportunidads) {
        this.subsectorOportunidads = subsectorOportunidads;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<SubsectorFoco> getSubsectorFocos() {
        return this.subsectorFocos;
    }
    
    public void setSubsectorFocos(Set<SubsectorFoco> subsectorFocos) {
        this.subsectorFocos = subsectorFocos;
    }




}


