package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1



/**
 * SubsectorOportunidad generated by hbm2java
 */
public class SubsectorOportunidad  implements java.io.Serializable {


     private long suboId;
     private Oportunidad oportunidad;
     private Subsector subsector;

    public SubsectorOportunidad() {
    }

	
    public SubsectorOportunidad(long suboId) {
        this.suboId = suboId;
    }
    public SubsectorOportunidad(long suboId, Oportunidad oportunidad, Subsector subsector) {
       this.suboId = suboId;
       this.oportunidad = oportunidad;
       this.subsector = subsector;
    }
   
    public long getSuboId() {
        return this.suboId;
    }
    
    public void setSuboId(long suboId) {
        this.suboId = suboId;
    }
    public Oportunidad getOportunidad() {
        return this.oportunidad;
    }
    
    public void setOportunidad(Oportunidad oportunidad) {
        this.oportunidad = oportunidad;
    }
    public Subsector getSubsector() {
        return this.subsector;
    }
    
    public void setSubsector(Subsector subsector) {
        this.subsector = subsector;
    }




}


