package com.andi.model;
// Generated 23/04/2016 10:02:31 PM by Hibernate Tools 4.3.1

import org.hibernate.annotations.Proxy;




/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuarioId;
     private Subsector subsector;
     private String usuarioNombre;
     private String usuarioPass;
     private String usuarioEmpresa;
     private String usuarioCargo;
     private String usuarioArea;

    public Usuario() {
    }

	
    public Usuario(String usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Usuario(String usuarioId, Subsector subsector, String usuarioNombre, String usuarioPass, String usuarioEmpresa, String usuarioCargo, String usuarioArea) {
       this.usuarioId = usuarioId;
       this.subsector = subsector;
       this.usuarioNombre = usuarioNombre;
       this.usuarioPass = usuarioPass;
       this.usuarioEmpresa = usuarioEmpresa;
       this.usuarioCargo = usuarioCargo;
       this.usuarioArea = usuarioArea;
    }
   
    public String getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(String usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Subsector getSubsector() {
        return this.subsector;
    }
    
    public void setSubsector(Subsector subsector) {
        this.subsector = subsector;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioPass() {
        return this.usuarioPass;
    }
    
    public void setUsuarioPass(String usuarioPass) {
        this.usuarioPass = usuarioPass;
    }
    public String getUsuarioEmpresa() {
        return this.usuarioEmpresa;
    }
    
    public void setUsuarioEmpresa(String usuarioEmpresa) {
        this.usuarioEmpresa = usuarioEmpresa;
    }
    public String getUsuarioCargo() {
        return this.usuarioCargo;
    }
    
    public void setUsuarioCargo(String usuarioCargo) {
        this.usuarioCargo = usuarioCargo;
    }
    public String getUsuarioArea() {
        return this.usuarioArea;
    }
    
    public void setUsuarioArea(String usuarioArea) {
        this.usuarioArea = usuarioArea;
    }




}


